
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class FeedItem
{

    public int Id { get; set; }

    public int FeedId { get; set; }

    public System.DateTime Published { get; set; }

    public string Url { get; set; }

    public string Guid { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Tags { get; set; }



    public virtual Feed Feed { get; set; }

}

}
