//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public Feed()
        {
            this.UpdateInterval = 60F;
            this.FeedItem = new HashSet<FeedItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RssUrl { get; set; }
        public float UpdateInterval { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual ICollection<FeedItem> FeedItem { get; set; }
    }
}
